### ISSUE TITLE
The source becomes slow in non-lsp buffer

### ISSUE THREAD

**Issue by matsui54** [Shougo/ddc-source-nvim-lsp#22]
# Problems summary
Nvim-lsp source becomes very slow in buffers which language server doesn't attach.

## Expected
Completion menu appears immediately after typing.

## Environment Information

- ddc.vim version (SHA1): https://github.com/Shougo/ddc.vim/commit/e1f2e7657f2a7c9a27ff62d7ff60e41009f527c9

- denops.vim version (SHA1): https://github.com/Shougo/ddc.vim/commit/e1f2e7657f2a7c9a27ff62d7ff60e41009f527c9

- deno version(`deno -V` output): `deno 1.14.3 (release, x86_64-unknown-linux-gnu)`

- OS: arch linux

- neovim/Vim `:version` output: `NVIM v0.6.0-dev+366-g270cc1d70`

- `:checkhealth` or `:CheckHealth` result(neovim only): No problem

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.cache/dein/repos/github.com/vim-denops/denops.vim/
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddc.vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddc-nvim-lsp
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddc-around
set runtimepath+=~/.cache/dein/repos/github.com/neovim/nvim-lspconfig

call ddc#custom#patch_global('sources', ['nvim-lsp', 'around'])
call ddc#custom#patch_global('sourceOptions', {
      \ 'around': {'mark': 'A'},
      \ 'nvim-lsp': {'mark': 'lsp'},
      \ })
call ddc#enable()
lua require'lspconfig'.clangd.setup{}

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start nvim and type something like `hoge ho`.
2. Complete menu appears with delay of few seconds (This does not occur in c buffer which server attaches).

The delay time seems 2000 ms which is `timeout` of ddc-source-option.
I tried this config and the delay became shorter.
```vim
call ddc#custom#patch_global('sourceOptions', {'_': {'timeout': 100}})
```

## Screenshot (if possible)

https://user-images.githubusercontent.com/63794197/136915709-cdbefcdb-5b12-4f0e-b134-077d20d22cc0.mp4

**Comment by matsui54** [comment]
The problem occurs after #21.

**Comment by LumaKernel** [comment]
thank you. https://github.com/Shougo/ddc-nvim-lsp/pull/23 may fix this.
