### ISSUE TITLE
[Question] CSS LSP input.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddc-source-nvim-lsp#24]
# Problems summary
I don't know the proper setting for CSS forceCompletionPattern.
Completion candidates that start with a colon are not entered correctly.

## Expected
Find out the proper settings for the CSS forceCompletionPattern.

## Environment Information

- ddc.vim version (SHA1): 9c43cf1f89136a2b6592e694a693c9676a3ffaa7

- ddc-nvim-lsp version (SHA1): 75b53823d900d9be55a77fe2d096d54d0eaa262c

- denops.vim version (SHA1): f575cd5c56787b764e064da845b72ceea184ea97

- deno version(`deno -V` output): 1.15.1

- OS: Mac

- neovim/Vim `:version` output: 0.5.1

- `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif
let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif
call dein#begin(s:dein_dir, expand('<sfile>'))
call dein#add('neovim/nvim-lspconfig')
call dein#add('vim-denops/denops.vim')
call dein#add('Shougo/ddc.vim')
call dein#add('Shougo/ddc-matcher_head')
call dein#add('Shougo/ddc-sorter_rank')
call dein#add('Shougo/ddc-nvim-lsp')
call dein#end()
call dein#save_state()
if has('vim_starting') && dein#check_install()
    call dein#install()
endif
inoremap jj <ESC>
lua << EOF
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
require"lspconfig".cssls.setup {
  capabilities = capabilities,
}
EOF
call ddc#custom#patch_global('sources', ['nvim-lsp'])
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'minAutoCompleteLength': 1,
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank']},
      \ 'nvim-lsp': {
      \   'forceCompletionPattern': '\:\w*' },
      \ })
call ddc#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Enter `html:` in the CSS file.

## nvim-cmp setup
```vim
if &compatible
    set nocompatible
endif
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif
let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif
call dein#begin(s:dein_dir, expand('<sfile>'))
call dein#add('neovim/nvim-lspconfig')
call dein#add('hrsh7th/nvim-cmp')
call dein#add('hrsh7th/cmp-nvim-lsp')
call dein#end()
call dein#save_state()
if has('vim_starting') && dein#check_install()
    call dein#install()
endif
inoremap jj <ESC>
lua << EOF
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
require"lspconfig".cssls.setup {
  capabilities = capabilities,
}
local cmp = require('cmp')
cmp.setup {
    mapping = {
        ['<C-p>'] = cmp.mapping.select_prev_item(),
        ['<C-n>'] = cmp.mapping.select_next_item(),
    },
    sources = {
        { name = 'nvim_lsp' }
    },
}
EOF
```

## Screenshot (if possible)
ddc-nvim-lsp
![スクリーンショット 2021-10-14 23 24 11](https://user-images.githubusercontent.com/3197942/137343417-486b902d-4cc0-40c8-8e6a-3345fd54ce51.png)

nvim-cmp
![スクリーンショット 2021-10-14 23 41 15](https://user-images.githubusercontent.com/3197942/137343473-39befabf-0297-49c1-8537-602188665de3.png)

**Comment by nabezokodaikon** [comment]
After all I couldn't do it well.
The settings are as follows.
```vim
call ddc#custom#patch_filetype(['css'], {
      \ 'keywordPattern': '[a-zA-Z_:]\w*',
      \ 'smartCase': v:true,
      \ })
call ddc#custom#patch_filetype(['css'], 'sources', ['nvim-lsp'])
call ddc#custom#patch_filetype(['css'], 'sourceOptions', {
      \ 'nvim-lsp': {
      \   'forceCompletionPattern': ':\s\w*' },
      \ })
```
The item called Unit of LSP is not completed correctly.
![タイトルなし](https://user-images.githubusercontent.com/3197942/137588333-674e1051-eb2c-4a7e-8302-244b0e47003a.gif)

**Comment by Shougo** [comment]
Your keyword pattern is wrong.  You should know what is you have set.

``      \ 'keywordPattern': '[a-zA-Z_:]\w*', does not match `10`.
You need to use `\w*` instead.

**Comment by Shougo** [comment]
What is the general?  You need to configure plugins as you need.

**Comment by Shougo** [comment]
I think nvim-lsp may set better pattern automatically from LSP server.
But it is not my policy.  It is too complicated and it is not easy to configure by users.
